env:
  browser: true
  commonjs: true
  es2021: true
plugins:
  - prettier
extends:
  - airbnb-base
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns:
  - node_modules/
  - dist/
  - .eslintrc.yml
  - '*.config.cjs'
rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
