root: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
plugins:
  - prettier
env:
  browser: true
  commonjs: true
  es2021: true
globals:
  expect: true
  it: true
  describe: true
  Drupal: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns:
  - node_modules/
  - dist/
  - .eslintrc.yml
  - '*.config.js'
rules:
  strict: 0
  import/no-extraneous-dependencies: 0
  prettier/prettier: 0
settings:
  import/ignore:
    - \.(css)$
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
      moduleDirectory:
        - node_modules
        - source/
